### ISSUE TITLE
lodash is modified for all npm packages using the same lodash version

### ISSUE THREAD

**Issue by axten** [gruntjs/grunt-legacy-util#17]
see https://github.com/gruntjs/grunt-legacy-log/issues/26
grunt-legacy-util has the same problem and overrides the lodash functions for **all npm packages** using the same lodash version!

https://github.com/gruntjs/grunt-legacy-util/blob/8034177cdaa2638a823fd960c0a2c5c180d064b4/index.js#L30-L32

**Comment by ntwb** [comment]
Thanks @shama 👍
